q = chr(96) * 3
lines = []
lines.append("# Block-schema algorithm ARM Adaptation under DBI")
lines.append("")
lines.append(q + "mermaid")
lines.append("flowchart TD")
lines.append("")
lines.append("    Start([Start ARM]) --> P1")
lines.append("")
lines.append("    %% === STAGE 1: PATH SETUP ===")
lines.append("    P1[Select source dir PATCH_IN/xxx]")
lines.append("    P1 --> P2[Auto-fill result dir PATCH_OUT/xxx]")
lines.append("    P2 --> P3{Both dirs<br/>specified?}")
lines.append("    P3 -->|No| P1")
lines.append("    P3 -->|Yes| R1")
lines.append("")
lines.append("    %% === STAGE 2: RUBRICATOR RULES ===")
lines.append("    R1[Load rubricator]")
lines.append("    R1 --> R2[Load 1.RUBRICATOR_FILES.md]")
lines.append("    R2 --> R3[Load 4.RUBRICATOR_PROMPTS.json]")
lines.append("    R3 --> R4[Fill rules Treeview]")
lines.append("    R4 --> R5[User selects<br/>rules e.g. v50]")
lines.append("    R5 --> R6{Any rule<br/>selected?}")
lines.append("    R6 -->|No| R5")
lines.append("    R6 -->|Yes| S1")
lines.append("")
lines.append("    %% === STAGE 3: SCAN CODE F5 ===")
lines.append("    S1[Start scan<br/>threading.Thread]")
lines.append("    S1 --> S2[Lock buttons]")
lines.append("    S2 --> S3[Create PLPlusScanner]")
lines.append("    S3 --> S4[scanner.scan_directory<br/>recursive *.plp]")
lines.append("    S4 --> S5[Progress 50%]")
lines.append("    S5 --> S6[Generate report<br/>scan_report_*.md]")
lines.append("    S6 --> S7[Show stats<br/>files + issues]")
lines.append("    S7 --> S8[Save self.scan_results]")
lines.append("    S8 --> S9[Unlock buttons]")
lines.append("    S9 --> F1")
lines.append("")
lines.append("    %% === STAGE 4: FIX CODE F6 ===")
lines.append("    F1[Start fix<br/>threading.Thread]")
lines.append("    F1 --> F2[Lock buttons]")
lines.append("    F2 --> F3{preserve_structure<br/>= True?}")
lines.append("    F3 -->|Yes| F4[Copy structure<br/>_copy_directory_structure]")
lines.append("    F3 -->|No| F5")
lines.append("    F4 --> F5[Create PLPlusScanner<br/>+ scan]")
lines.append("    F5 --> F6{total_issues<br/>== 0?}")
lines.append("    F6 -->|Yes| F14[No problems<br/>found end]")
lines.append("    F6 -->|No| F7[Create PLPlusFixer]")
lines.append("    F7 --> F8{preserve_structure?}")
lines.append("    F8 -->|Yes| F9[final_results_dir<br/>= result_dir]")
lines.append("    F8 -->|No| F10[final_results_dir<br/>= result_dir/<br/>source_vYYYYMMDD_HHMMSS]")
lines.append("    F9 --> F11[fixer.fix_directory<br/>apply fixes]")
lines.append("    F10 --> F11")
lines.append("    F11 --> F12[Save log<br/>fix_log_*.md]")
lines.append("    F12 --> F13[Show results<br/>processed + fixed + created]")
lines.append("    F13 --> F14{Auto-archive<br/>preserve_structure?}")
lines.append("    F14 -->|Yes| F15[Run _run_archive]")
lines.append("    F14 -->|No| F16")
lines.append("    F15 --> F16[Unlock buttons]")
lines.append("    F16 --> A1")
lines.append("")
lines.append("    %% === STAGE 5: ARCHIVE ===")
lines.append("    A1[Run archive<br/>_run_archive]")
lines.append("    A1 --> A2[Create ZIP<br/>zipfile.ZipFile]")
lines.append("    A2 --> A3[os.walk<br/>add files]")
lines.append("    A3 --> A4{Has .pck<br/>file?}")
lines.append("    A4 -->|Yes| A5[shutil.copy2<br/>source.pck to archive]")
lines.append("    A4 -->|No| A6[Log: .pck<br/>not found]")
lines.append("    A5 --> A7[zipf.write<br/>.pck to archive]")
lines.append("    A6 --> A8")
lines.append("    A7 --> A8[Copy .pck to<br/>PATCH_OUT parent]")
lines.append("    A8 --> A9[Progress 100%]")
lines.append("    A9 --> A10[Log: Archive created<br/>MessageBox]")
lines.append("    A10 --> End([End])")
lines.append("")
lines.append("    %% === HORIZONTAL LINKS ===")
lines.append("    style Start fill:#4CAF50,stroke:#2E7D32,stroke-width:3px,color:white")
lines.append("    style End fill:#4CAF50,stroke:#2E7D32,stroke-width:3px,color:white")
lines.append("    style P3 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style R6 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style F3 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style F6 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style F8 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style F14 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style A4 fill:#FF9800,stroke:#E65100,stroke-width:2px,color:white")
lines.append("    style P1,P2,R1,R2,R3,R4,R5,S1,S2,S3,S4,S5,S6,S7,S8,S9,F1,F2,F4,F5,F7,F9,F10,F11,F12,F13,F15,F16,A1,A2,A3,A5,A6,A7,A8,A9,A10 fill:#2196F3,stroke:#1565C0,stroke-width:2px,color:white")
lines.append("")
lines.append("    classDef stage1 fill:#E3F2FD,stroke:#1565C0,stroke-width:1px")
lines.append("    classDef stage2 fill:#E8F5E9,stroke:#2E7D32,stroke-width:1px")
lines.append("    classDef stage3 fill:#FFF3E0,stroke:#E65100,stroke-width:1px")
lines.append("    classDef stage4 fill:#F3E5F5,stroke:#6A1B9A,stroke-width:1px")
lines.append("    classDef stage5 fill:#E0F7FA,stroke:#00838F,stroke-width:1px")
lines.append("")
lines.append("    class P1,P2,P3 stage1")
lines.append("    class R1,R2,R3,R4,R5,R6 stage2")
lines.append("    class S1,S2,S3,S4,S5,S6,S7,S8,S9 stage3")
lines.append("    class F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16 stage4")
lines.append("    class A1,A2,A3,A4,A5,A6,A7,A8,A9,A10 stage5")
lines.append(q)
lines.append("")
lines.append("## Description of 5 stages")
lines.append("")
lines.append("| Stage | Key | Description |")
lines.append("|-------|-----|-------------|")
lines.append("| 1. Path Setup | - | Specify source PATCH_IN and auto-fill result PATCH_OUT |")
lines.append("| 2. Rubricator Rules | - | Load 1.RUBRICATOR_FILES.md and 4.RUBRICATOR_PROMPTS.json select rules in Treeview |")
lines.append("| 3. Scan Code | F5 | Recursive scan *.plp via PLPlusScanner generate scan_report_*.md |")
lines.append("| 4. Fix Code | F6 | Copy structure scan apply fixes via PLPlusFixer save fix_log_*.md |")
lines.append("| 5. Archive | Auto/Button | Create ZIP archive copy .pck file save to PATCH_OUT |")
open("ALGORITHM_FLOWCHART.md","w",encoding="utf-8").write(chr(10).join(lines)+chr(10))
print("Written " + str(len(lines)) + " lines")
